config/routes.rb
Rails.application.routes.draw do
    root "pages#index"
    post "/send_message", to: "pages#send_message"
    get '/work', to: "pages#work"
    get '/photography', to: "pages#photography"
    resources :books, only: [:index, :show]
    get '/contact', to: "pages#contact"
end

app/models/message.rb
class Message < ActiveRecord::Base
  attr_accessor :human

  validates :name, presence: { message: "Name can't be blank" }
  validates :content, presence: { message: "Message can't be blank" }
  validates :email,
            presence: { message: "Email can't be blank" },
            format: { with: /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\Z/i,
                      message: "Invalid email", if: 'email.present?' }
  validate :human_check

  private

  def human_check
    if human == "1"
      errors.add(:base, "Leave the checkbox unchecked if you're a human")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @available_years = Dir.glob(Rails.root.join('app', 'books', '*'))
                         .select { |path| File.directory?(path) }
                         .map { |path| path.split('/').last }
                         .sort
                         .reverse

    year_param = ActionController::Base.helpers.sanitize(params[:year])
    @current_year =
      if @available_years.include?(year_param)
        year_param
      else
        Time.zone.now.year.to_s
      end

    @books = []
    Dir.glob(Rails.root.join('app', 'books', @current_year, '*.yml')) do |book_file|
      @books << YAML.load_file(book_file)
    end
    @books.sort_by! { |book| Date.parse(book['date']) }.reverse!
  end

  def show
    title = ActionController::Base.helpers.sanitize(params[:id])
    file_path = Dir.glob(Rails.root.join('app', 'books', "**/*"))
                   .select { |path| path.split('/').last == "#{title}.yml" }
                   .first

    if file_path && File.file?(file_path)
      @book = YAML.load_file(file_path)
    else
      raise ActionController::RoutingError, 'Not Found'
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def send_message
    @contact_message = Message.new(message_params)
    if @contact_message.save
      render json: @contact_message, status: :created
    else
      render json: @contact_message.errors, status: :unprocessable_entity
    end
  end

  def books
    @books = []
    Dir.glob(Rails.root.join('app', 'books', '*.yml')) do |book_file|
      @books << YAML.load_file(book_file)
    end
    @books.sort_by! { |book| Date.parse(book['date']) }.reverse!
  end

  private

  def message_params
    params.require(:message).permit(:name, :email, :content, :human)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

def full_title(page_title)
  base_title = "Annabel"
  page_title.empty? ? base_title : "#{base_title} | #{page_title}"
end

def meta_description(description)
  base_description = "Annabel Dunstone Gray"
  description.empty? ? base_description : description
end

def meta_keywords(page_keywords)
  base_keywords = "Annabel, Dunstone, Gray, Annabel Dunstone Gray, web, code, programming, web developer"
  if page_keywords.empty?
    base_keywords
  else
    "#{base_keywords}, #{page_keywords}"
  end
end

def nav_link(link_text, link_path, class_name=nil)
  if current_page?(link_path) || request.path.include?(link_path)
    content_tag(:li, class: "active #{class_name}") do
      link_to(link_text, link_path)
    end
  else
    content_tag(:li, class: class_name) do
      link_to(link_text, link_path)
    end
  end
end

end

app/views/books/index.haml
- provide(:title, "Books")
.headline-books
  .container
    .section-title
      .text-column
        .header Books
        .text
          Welcome to my books page! Here you can find most of the books I've read in the last couple years (the rest are on
          <a href="http://www.goodreads.com/annabelgray" target="_blank">goodreads</a>).


.container
  .row
    .year-buttons-container
      - @available_years.each do |year|
        - class_name = "books-year " + year
        - class_name += " active" if @current_year == year
        = link_to year, books_path(year: year), class: class_name
  .row.books-row
    - @books.each do |book|
      .books-column
        .book{ class: ("featured" if book['stars'] == 5)}
          = image_tag "books/#{book['slug']}.jpg"
          .book-rating
            - book['stars'].times do
              %span.star.star-full &#9733;
            - (5 - book['stars']).times do
              %span.star &#9733;
          .date= book['date']
          - if book['description']
            = link_to "About book", book_path(book['slug']), class: "review-link"
          - if book['link']
            = link_to book['link'], class: "shop-link", target: "_blank" do
              .glyphicon.glyphicon-share

app/views/books/show.haml
- provide(:title, "#{@book['title']}")

.review-container
  .container
    .row
      .review-column
        .book-meta
          = image_tag "books/#{@book['slug']}.jpg"
          .book-title= @book['title']
          .book-author by #{@book['author']}
          .publisher
            =@book['publisher']
            = link_to @book['link'], class: "shop-link", target: "_blank" do
              %span Buy book on Amazon
              .glyphicon.glyphicon-share
        .quote= @book['quote']
        .review= @book['description'].html_safe

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title><%= full_title(yield(:title)) %></title>
        <meta content="<%= meta_description(yield(:description)) %>" name="description">
        <meta content="<%= meta_keywords(yield(:keywords)) %>" name="keywords">
        <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport">
        <meta name="mobile-web-app-capable" content="yes">
        <meta property="og:title" content="Annabel Dunstone Gray" />
        <meta property="og:type" content="website" />
        <meta property="og:description" content="Web Developer" />
        <meta property="og:url" content="http://annabeldunstone.com/" />
        <meta property="og:image" content="<%= image_path 'site_preview.png' %>" />
        <%= stylesheet_link_tag    'application', media: 'all' %>
        <%= javascript_include_tag 'application' %>
        <%= respond_include_tags %>
        <%= csrf_meta_tags %>

        <%= favicon_link_tag %>
        <link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'apple-touch-icon-180x180.png' %>">

      <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
      <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
      <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
      <![endif]-->
    </head>
    <body>
        <div class="content">
            <%= render "partials/navbar" %>
            <div class="content-wrap">
                <div class="main-content">
                    <%= yield %>
                </div>
            </div>
        </div>
        <%= render "partials/footer" unless current_page?(root_url) %>
        <% if Rails.env.production? %>
        <script>
            (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
                    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
            })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

            ga('create', 'UA-63797749-1', 'auto');
            ga('send', 'pageview');
        </script>
        <% end %>
    </body>
</html>

app/views/pages/contact.haml
- provide(:title, "Contact")
.headline-contact
  .container
    .section-title
      .text-column
        .header Get in touch!
        .text
          While I'm not actively seeking new projects at the moment, I'm always open to hearing about new and
          exciting ideas. If you have a project in mind and think we would make a good team, or if you just want
          to say hello, please feel free to drop me a line!

.container
  .contact-form-row
    .inputs-column
      = form_for :message, url: send_message_path, method: :post, html: { role: 'form', id: 'contact-form' } do |f|
        = f.label(:human, "If you're a human, leave this unchecked", style: "display: none")
        = f.check_box(:human, style: "display: none")
        .form-group
          = f.text_field :name, class: "form-control", placeholder: "Name"
          .name-error.error-message
        .form-group
          = f.text_field :email, class: "form-control", placeholder: "Email"
          .email-error.error-message
        .form-group
          = f.text_area :content, class: "form-control", placeholder: "Your message goes here..."
          .content-error.error-message
        .button-container
          = submit_tag "Submit", class: "btn contact-form-submit"
          .message-success

app/views/pages/index.haml
#index
  .index-row
    .computer
      = image_tag "me.png"
    .text
      .name Annabel Dunstone Gray
      .title.developer
        = link_to "Frontend Engineer", work_path
      .title.designer
        = link_to "Occasional Designer", work_path
      .title.photographer
        = link_to "Amateur Photographer", photography_path
      .title.baker Experimental Baker
      .title.reader
        = link_to "Avid Reader", books_path

app/views/pages/photography.haml
- provide(:title, "Photography")
.container
  #lightgallery
    .image-row
      = link_to image_path('photography/structure1.jpg') do
        = image_tag('photography/structure1.jpg', class: 'image-thumbnail')
      = link_to image_path('photography/westonsupermare1.jpg') do
        = image_tag('photography/westonsupermare1.jpg', class: 'image-thumbnail')
      = link_to image_path('photography/westonsupermare3.jpg') do
        = image_tag('photography/westonsupermare3.jpg', class: 'image-thumbnail')
      = link_to image_path('photography/balea6.jpg') do
        = image_tag('photography/balea6.jpg', class: 'image-thumbnail')
      = link_to image_path('photography/light2.jpg') do
        = image_tag('photography/light2.jpg', class: 'image-thumbnail')
      = link_to image_path('photography/structure3.jpg') do
        = image_tag('photography/structure3.jpg', class: 'image-thumbnail')
      = link_to image_path('photography/chair.jpg') do
        = image_tag('photography/chair.jpg', class: 'image-thumbnail')
      = link_to image_path('photography/lockhart5.jpg') do
        = image_tag('photography/lockhart5.jpg', class: 'image-thumbnail')
      = link_to image_path('photography/grammy1.jpg') do
        = image_tag('photography/grammy1.jpg', class: 'image-thumbnail')
      = link_to image_path('photography/gasstation.jpg') do
        = image_tag('photography/gasstation.jpg', class: 'image-thumbnail')
      = link_to image_path('photography/balea2.jpg') do
        = image_tag('photography/balea2.jpg', class: 'image-thumbnail')
      = link_to image_path('photography/saddle.jpg') do
        = image_tag('photography/saddle.jpg', class: 'image-thumbnail')
      = link_to image_path('photography/westonsupermare2.jpg') do
        = image_tag('photography/westonsupermare2.jpg', class: 'image-thumbnail')
      = link_to image_path('photography/structure4.jpg') do
        = image_tag('photography/structure4.jpg', class: 'image-thumbnail')
      = link_to image_path('photography/light1.jpg') do
        = image_tag('photography/light1.jpg', class: 'image-thumbnail')
      = link_to image_path('photography/grammy2.jpg') do
        = image_tag('photography/grammy2.jpg', class: 'image-thumbnail')
      = link_to image_path('photography/lockhart1.jpg') do
        = image_tag('photography/lockhart1.jpg', class: 'image-thumbnail')
      = link_to image_path('photography/portraitoman.jpg') do
        = image_tag('photography/portraitoman.jpg', class: 'image-thumbnail')
      = link_to image_path('photography/lockhart2.jpg') do
        = image_tag('photography/lockhart2.jpg', class: 'image-thumbnail')
      = link_to image_path('photography/lockhart3.jpg') do
        = image_tag('photography/lockhart3.jpg', class: 'image-thumbnail')
      = link_to image_path('photography/lockhart4.jpg') do
        = image_tag('photography/lockhart4.jpg', class: 'image-thumbnail')
      = link_to image_path('photography/portraitengland.jpg') do
        = image_tag('photography/portraitengland.jpg', class: 'image-thumbnail')
      = link_to image_path('photography/structure2.jpg') do
        = image_tag('photography/structure2.jpg', class: 'image-thumbnail')
      = link_to image_path('photography/lockhart6.jpg') do
        = image_tag('photography/lockhart6.jpg', class: 'image-thumbnail')
      = link_to image_path('photography/lockhart7.jpg') do
        = image_tag('photography/lockhart7.jpg', class: 'image-thumbnail')
      = link_to image_path('photography/portraitsudan.jpg') do
        = image_tag('photography/portraitsudan.jpg', class: 'image-thumbnail')
      = link_to image_path('photography/shadow1.jpg') do
        = image_tag('photography/shadow1.jpg', class: 'image-thumbnail')
      = link_to image_path('photography/portraitscotland.jpg') do
        = image_tag('photography/portraitscotland.jpg', class: 'image-thumbnail')
      = link_to image_path('photography/structure5.jpg') do
        = image_tag('photography/structure5.jpg', class: 'image-thumbnail')
      = link_to image_path('photography/lockhart8.jpg') do
        = image_tag('photography/lockhart8.jpg', class: 'image-thumbnail')

app/views/pages/work.haml
- provide(:title, "Work")
.work-block
  .container
    .work-row
      .project-column
        .light-blue.hover-tile-outer
          .hover-tile-container
            .hover-tile.hover-tile-visible
              = image_tag "work/gitlab-com.png"
              %button.btn.work-info-button
                .glyphicon.glyphicon-plus.light-blue
            .hover-tile.hover-tile-hidden.light-blue
              .tile-content
                .work-name GitLab.com
                = link_to "View Site", "https://about.gitlab.com/", class: "btn light-blue-btn", target: "_blank"
                .header Skills strengthened:
                .skills Middleman, Ruby, JavaScript
      .project-column
        .dark-pink.hover-tile-outer
          .hover-tile-container
            .hover-tile.hover-tile-visible
              = image_tag "work/gitlab-app.png"
              %button.btn.work-info-button
                .glyphicon.glyphicon-plus.dark-pink
            .hover-tile.hover-tile-hidden.dark-pink
              .tile-content
                .work-name GitLab CE/EE
                = link_to "View Repo", "https://gitlab.com/gitlab-org/gitlab-ce", class: "btn dark-pink-btn", target: "_blank"
                .header Skills strengthened:
                .skills SCSS, Rails, Vue.js, RSpec, ES6
      .project-column
        .dotrebate.hover-tile-outer
          .hover-tile-container
            .hover-tile.hover-tile-visible
              = image_tag "work/dotrebate.png"
              %button.btn.work-info-button
                .glyphicon.glyphicon-plus.dotrebate
            .hover-tile.hover-tile-hidden.dotrebate
              .tile-content
                .work-name Dot Rebate
                .coming-soon Redesign still in progress- stay tuned!
                .header Skills strengthened:
                .skills Sketch, Photoshop, Rails
      .project-column
        .johndeere.hover-tile-outer
          .hover-tile-container
            .hover-tile.hover-tile-visible
              = image_tag "work/johndeere.png"
              %button.btn.work-info-button
                .glyphicon.glyphicon-plus.johndeere
            .hover-tile.hover-tile-hidden.johndeere
              .tile-content
                .work-name John Deere
                .header Skills strengthened:
                .skills Selenium, JUnit, Cucumber
      .project-column
        .hcsc.hover-tile-outer
          .hover-tile-container
            .hover-tile.hover-tile-visible
              = image_tag "work/hcsc.png"
              %button.btn.work-info-button
                .glyphicon.glyphicon-plus.hcsc
            .hover-tile.hover-tile-hidden.hcsc
              .tile-content
                .work-name HCSC Assistance Finder
                = link_to "View App", "http://assistancefinder.hcsc.net/assistance-finder/tx/en#/", class: "btn hcsc-btn", target: "_blank"
                .header Skills strengthened:
                .skills Spring, Java, Angular.js
      .project-column
        .lucid.hover-tile-outer
          .hover-tile-container
            .hover-tile.hover-tile-visible
              = image_tag "work/lucid.png"
              %button.btn.work-info-button
                .glyphicon.glyphicon-plus.lucid
            .hover-tile.hover-tile-hidden.lucid
              .tile-content
                .work-name Lucid
                .header Skills strengthened:
                .skills Angular.js, SASS
      .project-column
        .mercaris.hover-tile-outer
          .hover-tile-container
            .hover-tile.hover-tile-visible
              = image_tag "work/mercaris.png"
              %button.btn.work-info-button
                .glyphicon.glyphicon-plus.mercaris
            .hover-tile.hover-tile-hidden.mercaris
              .tile-content
                .work-name Mercaris
                = link_to "View App", "http://www.mercaris.com/", class: "btn mercaris-btn", target: "_blank"
                .header Skills strenghtened:
                .skills Rails, JavaScript, Ruby
      .project-column
        .flo.hover-tile-outer
          .hover-tile-container
            .hover-tile.hover-tile-visible
              = image_tag "work/flo.png"
              %button.btn.work-info-button
                .glyphicon.glyphicon-plus.flo
            .hover-tile.hover-tile-hidden.flo
              .tile-content
                .work-name Flo Music
                = link_to "View Site", "http://flomusic.com/", class: "btn flo-btn", target: "_blank"
                .header Skills strengthened:
                .skills Wordpress, PHP, SASS, JavaScript, Bootstrap, Grunt
      .project-column
        .masterlock.hover-tile-outer
          .hover-tile-container
            .hover-tile.hover-tile-visible
              = image_tag "work/masterlock.png", class: "masterlock-image"
              %button.btn.work-info-button
                .glyphicon.glyphicon-plus.masterlock
            .hover-tile.hover-tile-hidden.masterlock
              .tile-content
                .work-name Master Lock eLocks
                = link_to "View in Google Play", "https://play.google.com/store/apps/details?id=com.masterlock.ble.app", class: "btn masterlock-btn", target: "_blank"
                .header Skills strengthened:
                .skills Java, Android, Android libraries
      .project-column
        .light-blue.hover-tile-outer
          .hover-tile-container
            .hover-tile.hover-tile-visible
              = image_tag "work/mycareer.png"
              %button.btn.work-info-button
                .glyphicon.glyphicon-plus.light-blue
            .hover-tile.hover-tile-hidden.light-blue
              .tile-content
                .work-name Exelon myCareer
                = link_to "View Article", "http://www.chicagotribune.com/bluesky/originals/chi-exelon-mycareer-app-bsi-20141224-story.html", class: "btn light-blue-btn", target: "_blank"
                .header Skills strengthened:
                .skills Angular.js, LESS, HTML5, Agile methodologies, cross-browser testing
      .project-column
        .scorpioncf.hover-tile-outer
          .hover-tile-container
            .hover-tile.hover-tile-visible
              = image_tag "work/scorpioncf.png"
              %button.btn.work-info-button
                .glyphicon.glyphicon-plus.scorpioncf
            .hover-tile.hover-tile-hidden.scorpioncf
              .tile-content
                .work-name Scorpion Crossfit
                = link_to "View App", "https://www.scorpioncrossfit.net/", class: "btn scorpioncf-btn", target: "_blank"
                .header Skills strengthened:
                .skills Rails, SASS, Ruby Slim, Design, Coffeescript
      .project-column
        .dark-pink.hover-tile-outer
          .hover-tile-container
            .hover-tile.hover-tile-visible
              = image_tag "work/akta.png"
              %button.btn.work-info-button
                .glyphicon.glyphicon-plus.dark-pink
            .hover-tile.hover-tile-hidden.dark-pink
              .tile-content
                .work-name AKTA.com
                .coming-soon Acquired by Salesforce in 2015
                .coming-soon Re-branded as Salesforce Experience Design
                .header Skills strengthened:
                .skills PHP, Wordpress, CSS, AJAX

app/views/partials/_footer.haml
.footer-block
  .text-fill
    %span.text-background Buzzwords • Grunt • Android Studio • JavaScript • Objective-C • jQuery • haml • |
    HTML5 • PHOTOSHOP • Xcode • SCSS • JUnit • ANGULAR.JS • RUBY • Spring • RAILS • C++(just kidding) • LESS • git • |
    PHP • WORDPRESS • Rocket League • Java • SWIG • Compass • Sketch • Selenium • BUZZWORDS • COFFEESCRIPT  • |
    Buzzwords • Grunt • Android Studio • JavaScript • Objective-C • IntelliJ • jQuery • BUZZWORDS • haml • HTML5 • PHOTOSHOP • |
    Xcode • SCSS • JUnit • ANGULAR.JS • RUBY • Spring • RAILS • C++(just kidding) • LESS • git • PHP • WORDPRESS • |
    Java • SWIG • Compass • Sketch • Selenium • BUZZWORDS • COFFEESCRIPT  •
  .contact-content.container
    .icon-row
      .email-container
        = mail_to "annabel.dunstone@gmail.com"
        .underline
      .icon-container
        = link_to "https://gitlab.com/u/annabeldunstone", target: "_blank" do
          = image_tag('footer-icons/gitlab.png', class: 'contact-icon gitlab')
        = link_to "https://www.linkedin.com/in/annabeldunstone", target: "_blank" do
          = image_tag('footer-icons/linkedin.png', class: 'contact-icon linkedin')
        = link_to "https://github.com/annabel", target: "_blank" do
          = image_tag('footer-icons/github.png', class: 'contact-icon github')
        = link_to "https://instagram.com/annabeldunstone/", target: "_blank" do
          = image_tag('footer-icons/instagram.png', class: 'contact-icon instagram')
        = link_to "https://dribbble.com/annabeldunstone", target: "_blank" do
          = image_tag('footer-icons/dribbble.png', class: 'contact-icon dribbble')
        = link_to "http://www.goodreads.com/annabelgray", target: "_blank" do
          = image_tag('footer-icons/goodreads.png', class: 'contact-icon goodreads')

app/views/partials/_navbar.haml
.container.navbird-desktop
  %ul.nav.navbar-content
    .content-left
      %li
        %a.home{href: '/'}
          = image_tag "apple-touch-icon-180x180.png", class: "icon"
          %span.home-text Annabel Dunstone Gray

    .content-right
      = nav_link('Work', work_path, 'work')
      = nav_link('books', books_path, 'books')
      = nav_link('Photography', photography_path, 'photography')
      = nav_link('Contact', contact_path, 'contact')